# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"

  # machine level provisioning
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y git
    dnf install -y rpcgen
    dnf install -y gnutls-devel
    dnf install -y libnl3-devel
    dnf install -y libxml2-devel
    dnf install -y libtirpc-devel
    dnf install -y yajl-devel
    dnf install -y device-mapper-devel
    dnf install -y libtool
    dnf install -y patch
    dnf install -y libxslt
    dnf install -y make
    dnf install -y libpciaccess-devel
    sudo -u vagrant bash -c 'git clone https://libvirt.org/git/libvirt.git' 2> /dev/null || (cd libvirt; git pull)
  SHELL
end

