# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"
 
  # use libvirt
  config.vm.provider "libvirt" do |lv|
    lv.memory = "2048"
  end

  # machine level provisioning
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y bridge-utils
    dnf install -y openvswitch
    dnf install -y tcpdump
    systemctl enable openvswitch
    systemctl start openvswitch
  SHELL
end

